name: Cargo Audit
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 9 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-audit:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v4.1.1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # was: @master
        with:
          toolchain: stable

      - name: Install cargo-audit
        uses: taiki-e/install-action@b8cecb83565409bcc297b2df6e77f030b2a468d5 # v2
        with:
          tool: cargo-audit

      - name: Run cargo audit
        run: cargo audit
